# Main Jekyll Configuration file.
#
# Jekyll needs to be restarted if you make any changes.
# For more information see the documentation.

# Basic site settings.
locale: "nl"
timezone: Europe/Amsterdam
domain: "www.onslesmateriaal.nl"
baseurl: "/"
url: ""

# Page content variables.
title: "Ons Lesmateriaal"
short: "OLM"
description: "Onder het motto “ons lesmateriaal - passend en professioneel” werkt een community van informatica-docenten en andere experts aan open leermateriaal voor de keuzethemas van het vak informatica in het VO. Deze community wordt georganiseerd door de vakvereniging i&i - voor docenten informatica en digitale geletterdheid. Het startschot voor deze community is gegeven op de i&i conferentie van 10 november 2022. Met deze community wil i&i het eigenaarschap van dit lesmateriaal zoveel mogelijk bij de docenten leggen. Op deze website zijn de actuele ontwikkelingen rond deze community te volgen."
kvk: "KvK 40481134 te Utrecht"

# Landing page hero variables.
hero:
  title: "Ons Lesmateriaal"
  lead: "Passend & Professioneel, met de kracht van samen werken we aan goed lesmateriaal voor informatica."

# Social variables.
twitter: "@ieni"
linkedin: "company/1526376"
linkedingroup: "groups/72298"

# Brand logos and icon paths.
logo:
  dark: "/assets/img/brand/icon-500-black.svg"
  light: "/assets/img/brand/icon-500-white.svg"
header:
  dark: "/assets/img/brand/header-dark.svg"
  light: "/assets/img/brand/header-light.svg"
icon:
  x32: "/assets/img/brand/icon-32.jpg"
  x180: "/assets/img/brand/icon-180.jpg"
  x192: "/assets/img/brand/icon-192.jpg"
  x270: "/assets/img/brand/icon-270.jpg"

# Global site defaults.
defaults:
  page_header: "/assets/img/content/default_page_header.jpg"

# API credentials / Site Keys.
# Keys are whitelisted for this specific domain and intended for front-end
# usage. They can thus be safely committed to this public repository.
credentials:
  recaptcha: "6LeeL0sUAAAAAD56p3YXokZIxy63PIjZrbAb_BXP"
  postcode: "daf8119e-0762-4326-b7f8-32504837b0c4"
  gs: "AKfycbyKZc95GP-JBDUbq-Og_8jB7PvTYhnzlWnOadhz8MRpG5dxHyc"

# Jekyll collections for pagination.
# For more information on collections see the Jekyll documentation.
collections:
  pages:
    output: true
    permalink: /:title
  posts:
    permalink: /nieuws/:title/
  projects:
    output: true
    permalink: /projecten/:title/
  team:
    output: false

exclude: [ "CNAME", ".gitignore", "README.md", "Gemfile" ]
